//code written for practice robot

#pragma config(Motor,  port1,           Right,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           Right2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Side,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Arm1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           Left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,          	Left,          tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()

{

	//claw is not closed
	int clawClosed;
	clawClosed = 0;


	while(1==1){

		//forward and back
		motor[Left] = vexRT[Ch3];
		motor[Left2] = vexRT[Ch3];
		motor[Right] = vexRT[Ch2];
		motor[Right2] = vexRT[Ch2];

		if(vexRT[Btn6U]==1){
		//raise arm
		motor[Arm1] = 100;
		}

		if(vexRT[Btn6D]==1){
		//lower arm
		motor[Arm1] = -100;
		}

		if(vexRT[Btn6U]==0){
			if(vexRT[Btn6D]==0){
				//stop arm
				motor[Arm1] = 0;
			}
		}


		//Open and close claw
		if(vexRT[Btn5U]==1){

			if(clawClosed == 0){
				//close claw
				motor[Claw] = 127;
				wait(0.7);
				motor[Claw] = 0;
				clawClosed = 1;
			}

			else{
				//open claw
				motor[Claw] = -127;
				wait(0.7);
				motor[Claw] = 0;
				clawClosed = 0;
			}

		}

		//side wheel to left
		while(vexRT[Btn8L]==1){
			motor[Side] = 127;
		}

		//side wheel to right
		if(vexRT[Btn8L]==0){
			if(vexRT[Btn8R]==1){
				motor[Side] = -127;
			}
			//side wheel stationary
			motor[Side] = 0;
		}

	}

}
